version: "3.8"
services:
  application:
    container_name: foodfinder-application
    image: node:lts-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/code 
    working_dir: /home/node/code/foodfinder-application
    depends_on:
      - backend
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    tty: true
    command: "npm run dev"
  backend:
    container_name: foodfinder-backend
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: foodfinder
    ports:
      - "27017:27017"
    volumes:
      - ./docker/foodfinder-backend/seed-mongodb.js:/docker-entrypoint-initdb.d/seed-mongodb.js
      - mongodb_data_container:/data/db


volumes:
  mongodb_data_container:

