services:

  backend:
    container_name: foodfinder-backend
    image: mongo:latest
    restart: always
    environment:
      DB_NAME: foodfinder
      MONGO_INITDB_DATABASE: foodfinder
    ports:
      - "27017:27017"
    volumes:
      # map seed script
      - ./.docker/foodfinder-backend/seed-mongodb.js:/docker-entrypoint-initdb.d/seed-mongodb.js
      # map mongoDB database to a shared volume to persist the data
      - mongodb_data_container:/data/db

  application:
    container_name: foodfinder-application
    image: node:lts-alpine
    # configure working directory for installing next.js
    working_dir: /home/node/code/foodfinder-application
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/code 
    depends_on:
      - backend
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    # keep container alive for installing next.js
    tty: true
    command: "npm run dev"

  jest:
    container_name: foodfinder-jest
    image: node:lts-alpine
    working_dir: /home/node/code/foodfinder-application
    volumes:
        - ./code:/home/node/code
    depends_on:
        - backend
        - application
    environment:
        - NODE_ENV=test
    tty: true
    command: "npm run testWatch"

volumes:
  mongodb_data_container: